/**
 * Onboarding — finalizes the first-login flow.
 *
 * POST body: { name: string, jurisdiction: string, registrationCategory: string }
 *
 * Behavior:
 *   1. Requires an authenticated session (no-op in preview mode — routes are open)
 *   2. Creates an organization row with slugified name as id
 *   3. Links the current user to the new org with role=owner
 *   4. Calls ensureTenant() to seed the authority corpus
 *   5. Returns the new organizationId
 */

import { NextRequest, NextResponse } from "next/server";
import { requireSession } from "../../../../lib/auth";
import { ensureTenant } from "../../../../lib/bootstrap";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface OnboardingInput {
  name?: string;
  jurisdiction?: string;
  registrationCategory?: string;
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}

export async function POST(req: NextRequest) {
  let session;
  try {
    session = await requireSession();
  } catch (err) {
    return NextResponse.json(
      { error: (err as Error).message || "Unauthorized" },
      { status: 401 },
    );
  }

  let body: OnboardingInput;
  try {
    body = (await req.json()) as OnboardingInput;
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  if (!body.name?.trim()) {
    return NextResponse.json({ error: "Organization name required" }, { status: 400 });
  }

  const slug = slugify(body.name);
  if (!slug) {
    return NextResponse.json(
      { error: "Organization name must contain letters or digits" },
      { status: 400 },
    );
  }

  // When DATABASE_URL is set, create the organization + user rows. The
  // organization `id` is a uuid (generated by Drizzle defaultRandom); the
  // user-chosen name is stored as `name` plus a slug for lookup. When
  // DATABASE_URL is unset, this is a preview-mode no-op and the org
  // identifier falls back to the slug.
  let organizationId = slug;
  if (process.env.DATABASE_URL) {
    try {
      const { unscopedDb, schema } = await import("@compliance-ai/db");
      const { eq } = await import("drizzle-orm");
      const db = unscopedDb();

      // Insert the org (unscoped: the org doesn't exist yet so RLS can't
      // be pre-filtered). On conflict with an existing slug, look it up.
      const [inserted] = await db
        .insert(schema.organizations)
        .values({ name: body.name, slug })
        .onConflictDoNothing({ target: schema.organizations.slug })
        .returning();

      const [org] = inserted
        ? [inserted]
        : await db
            .select()
            .from(schema.organizations)
            .where(eq(schema.organizations.slug, slug));

      if (!org) throw new Error("Failed to create or find organization");
      organizationId = org.id;

      // Link the current user to the org with owner role.
      await db
        .update(schema.users)
        .set({ organizationId, role: "owner" })
        .where(eq(schema.users.id, session.user.id));
    } catch (err) {
      return NextResponse.json(
        { error: `Failed to create organization: ${(err as Error).message}` },
        { status: 500 },
      );
    }
  }

  // Seed the tenant's authority corpus (idempotent).
  await ensureTenant(organizationId);

  return NextResponse.json({ organizationId, name: body.name }, { status: 201 });
}
